bar:
  location: top
  height: 25
  spacing: 0
  margin: 0
  background: 00000000
  font: JetBrainsMonoNerdFontMono:pixelsize=16

  center:
    - river:
        content:
          map:
            conditions:
              state == focused: {string: {text: "[{id}]", margin: 5, deco: {background: {color: 1e2132ff}}}}
    - clock:
        time-format: "%m.%d/%H:%M"
        content:
          string: {text: "{time}", margin: 5, deco: {background: {color: 84a0c6ff}}, foreground: 1e2132ff}
    - battery:
        name: macsmc-battery
        poll-interval: 20000
        content:
          map:
            conditions:
              state == charging:
                - string: {text: "{capacity}%", margin: 5, deco: {background: {color: b4be82ff}}, foreground: 1e2132ff}
              state == discharging:
                - string: {text: "{capacity}%", margin: 5, deco: {background: {color: e27878ff}}}
