add_newline = true

# format = """
# $directory\
# [/ ](white)\
# $git_branch\
# $git_status\
# [/ ](white)\
# $rust\
# $deno\
# $lua\
# $elixir\
# \n$character\
# """

format = '''
[<>>>>>>>>>>> ](bold green)$git_branch$git_status
$directory$character'''

[character]
success_symbol = "[>](bold green)"
error_symbol = "[X](bold red)"
vimcmd_symbol = "[<](bold green)"

[status]
symbol = "[x](bold red) "

[package]
disabled = true

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[git_branch]
symbol = "git "

[rust]
symbol = "rs "
format = "[$symbol]($style)"

[elixir]
symbol = "exs "
format = "[$symbol]($style)"

[lua]
symbol = "lua "
format = "[$symbol]($style)"

[deno]
symbol = "deno "
format = "[$symbol]($style)"

[directory]
read_only = " ro"

[memory_usage]
symbol = "memory "

[os.symbols]
Linux = "lnx "
Macos = "mac "

