#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# must manually update hash for yabai after every upgrade (shasum -a 256 $(which yabai))
# place hash into sudoers.d file (sudo visudo -f /private/etc/sudoers.d/yabai)

yabai -m config external_bar all:26:0

# Bar settings
# yabai -m config status_bar                   off

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_shadow                on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                on
yabai -m config window_border_width          2
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap
yabai -m config window_animation_duration    0.1

# general space settings
yabai -m config layout                       bsp
yabai -m config window_placement             second_child
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10
yabai -m config window_shadow                float

# Space Labels
yabai -m space --create 1 
yabai -m space --create 2
yabai -m space --create 3
yabai -m space --create 4
# yabai -m space --create 5
# yabai -m space --create 6
# yabai -m space --create 7
# yabai -m space --create 8
# yabai -m space --create 9

# Space Config
# yabai -m config --space 6 layout float

# Unmanaged
yabai -m rule --add app="^(System Preferences| Calculator|Archive Utility|balenaEtcher|zoom.us)$"  manage=off border=off
