I = {}

I.symbol_map = {
        Array = "[x] ",
        Boolean = "<-> ",
        Class = "\\=\\ ",
        Color = "#ff ",
        Constant = "[=] ",
        Constructor = "new ",
        Enum = "-|> ",
        EnumMember = "::",
        Event = "",
        Field = ".",
        File = "",
        Folder = "",
        Function = "f(x) ",
        Interface = ".=() ",
        Key = "> ",
        Keyword = "",
        Method = "f(x) ",
        Module = "|++| ",
        Namespace = "{x} ",
        Null = "\\0",
        Number = "000 ",
        Object = "[.*] ",
        Operator = "+-/ ",
        Package = "",
        Property = "",
        String = "\" ",
        Struct = ".= ",
        TypeParameter = "-<> ",
        Unit = "_",
        Variable = "x ",
}

return I
