#!/bin/sh

super="Mod4"
alt="Mod1"

# gsettings cmds
gsettings set org.gnome.desktop.wm.preferences button-layout ""

# app spawning
riverctl map normal $super Return spawn foot
riverctl map normal $super W spawn librewolf
riverctl map normal $super N spawn neovide
riverctl map normal $super Space spawn "tofi-drun --drun-launch=true"

riverctl map normal $super Q close
riverctl map normal $super+Shift Q exit

# send focused view to the top of the layout stack
riverctl map normal $super T zoom
riverctl map normal $super+Shift F toggle-float

# changing / swaping focused windows
riverctl map normal $super J focus-view next
riverctl map normal $super K focus-view previous
riverctl map normal $super+Shift J swap next
riverctl map normal $super+Shift K swap previous

# window movement
riverctl map normal $super+$alt H move left 100
riverctl map normal $super+$alt J move down 100
riverctl map normal $super+$alt K move up 100
riverctl map normal $super+$alt L move right 100

# window reszing
riverctl map normal $super+Fn H resize left 100
riverctl map normal $super+Fn J resize down 100
riverctl map normal $super+Fn K resize up 100
riverctl map normal $super+Fn L resize right 100

# snap window to anchor
riverctl map normal $super+Control H snap left
riverctl map normal $super+Control J snap down
riverctl map normal $super+Control K snap up
riverctl map normal $super+Control L snap right

# rivertile cmds
riverctl map normal $super Up send-layout-cmd rivertile "main-location up"
riverctl map normal $super Left send-layout-cmd rivertile "main-location left"
riverctl map normal $super Right send-layout-cmd rivertile "main-location right"
riverctl map normal $super Down send-layout-cmd rivertile "main-location down"

riverctl map normal $super+Control+Shift H send-layout-cmd rivertile "main-ratio +0.01"
riverctl map normal $super+Control+Shift L send-layout-cmd rivertile "main-ratio -0.01"
riverctl map normal $super+$alt+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $super+$alt+Shift L send-layout-cmd rivertile "main-count -1"

# media
riverctl map normal None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+; $HOME/.config/river/vol.sh"
riverctl map normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-; $HOME/.config/river/vol.sh"
riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle; $HOME/.config/river/vol.sh"
riverctl map normal None XF86MonBrightnessUp spawn "brightnessctl set +5%; $HOME/.config/river/bright.sh"
riverctl map normal None XF86MonBrightnessDown spawn "brightnessctl set 5%-; $HOME/.config/river/bright.sh"

# floating window conditions
riverctl float-filter-add app-id mako

# window and background decorations
riverctl border-color-focused 0x84a0c6
riverctl border-color-unfocused 0x1e2132
riverctl border-width 3

# autostart
riverctl spawn "exec dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus"
riverctl spawn "exec pipewire"
riverctl spawn "exec pipewire-pulse"
riverctl spawn "exec wireplumber"
riverctl spawn "exec swaybg -i ~/.config/river/tower_fog_mountain.jpg -m fill"
riverctl spawn "exec yambar"
riverctl spawn "exec mako"


# tags
for i in $(seq 1 9)
do
        tagmask=$((1 << ($i - 1)))

        riverctl map normal $super $i set-focused-tags $tagmask         # switch to tag
        riverctl map normal $super+Shift $i set-view-tags $tagmask      # move window to tag
        riverctl map normal $super+$alt $i toggle-focused-tags $tagmask
        riverctl map normal $super+$alt+Shift toggle-view-tags $tagmask
done

alltagmask=$(((1 << 32) - 1))

riverctl map normal $super 0 set-focused-tags $alltagmask
riverctl map normal $super+Shift 0 set-view-tags $alltagmask

riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 5 -main-ratio 0.50 -main-location left
