#!/bin/sh

super="Mod4"
alt="Mod1"

# gsettings cmds
gsettings set org.gnome.desktop.wm.preferences button-layout ""

# app spawning
riverctl map normal $super Return spawn wezterm
riverctl map normal $super W spawn qutebrowser
riverctl map normal $super Space spawn tofi-drun

riverctl map normal $super Q close
riverctl map normal $super+Shift Q exit

# send focused view to the top of the layout stack
riverctl map normal $super T zoom
riverctl map normal $super+Shift F toggle-float

# changing / swaping focused windows
riverctl map normal $super J focus-view next
riverctl map normal $super K focus-view previous
riverctl map normal $super+Shift J swap next
riverctl map normal $super+Shift K swap previous

# window movement
riverctl map normal $super+$alt H move left 100
riverctl map normal $super+$alt J move down 100
riverctl map normal $super+$alt K move up 100
riverctl map normal $super+$alt L move right 100

# window resziing
riverctl map normal $super+Shift H resize left 100
riverctl map normal $super+Shift J resize down 100
riverctl map normal $super+Shift K resize up 100
riverctl map normal $super+Shift L resize right 100

# snap window to anchor
riverctl map normal $super+Control H snap left
riverctl map normal $super+Control J snap down
riverctl map normal $super+Control K snap up
riverctl map normal $super+Control L snap right

# rivertile cmds
riverctl map normal $super Up send-layout-cmd rivertile "main-location up"
riverctl map normal $super Left send-layout-cmd rivertile "main-location left"
riverctl map normal $super Right send-layout-cmd rivertile "main-location right"
riverctl map normal $super Down send-layout-cmd rivertile "main-location down"

riverctl map normal $super+Control+Shift H send-layout-cmd rivertile "main-ratio +0.01"
riverctl map normal $super+Control+Shift L send-layout-cmd rivertile "main-ratio -0.01"
riverctl map normal $super+$alt+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $super+$alt+Shift L send-layout-cmd rivertile "main-count -1"

# media
riverctl map normal None XF86AudioRaiseVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
riverctl map normal None XF86AudioLowerVolume spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
riverctl map normal None XF86AudioMute spawn 'pactl set-sink-volume @DEFAULT_SINK@ 0%'
# riverctl map normal F11 XF86MonBrightnessUp spawn "brightnessctl set +5"
# riverctl map normal F12 XF86MonBrightnessUp spawn "brightnessctl set -5"

# about the brightness:
# i have searched around the /sys files for anything brightness related and i've only found the dirs
# pertaining to my keyboard
# no brightness files related to my external monitor have been found anywhere
# i can change the brightness among with controls on the monitor itself, but would like to set the
# actions to keybinds inside linux, any help is appreciated (the port is HDMI-A-1 and the brand is msi if that helps any)

# floating window conditions
riverctl float-filter-add app-id mako

# window and background decorations
riverctl border-color-focused 0x81a1c1
riverctl border-color-unfocused 0x3b4252
rivetctl border-width 3

#TODO: autostart
riverctl spawn "exec dbus-daemon --session --address=unix:path=$XDG_RUNTIME_DIR/bus"
riverctl spawn "exec pipewire"
riverctl spawn "exec wireplumber"
riverctl spawn "exec wbg ~/.config/river/darkblue_freeway_night.jpg"
riverctl spawn "exec waybar"
riverctl spawn "exec kanshi"
riverctl spawn "exec mako"

# tags
for i in $(seq 1 9)
do
        tagmask=$((1 << ($i - 1)))

        riverctl map normal $super $i set-focused-tags $tagmask         # switch to tag
        riverctl map normal $super+Shift $i set-view-tags $tagmask      # move window to tag
        riverctl map normal $super+$alt $i toggle-focused-tags $tagmask
        riverctl map normal $super+$alt+Shift toggle-view-tags $tagmask
done

alltagmask=$(((1 << 32) - 1))

riverctl map normal $super 0 set-focused-tags $alltagmask
riverctl map normal $super+Shift 0 set-view-tags $alltagmask

riverctl default-layout rivertile
rivertile -view-padding 5 -outer-padding 5 -main-ratio 0.50 -main-location left
