setopt HIST_IGNORE_ALL_DUPS # ignore all duplicate history entries
setopt CORRECT # spelling correction prompt
bindkey -v # vi editor default keymap

SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '

WORDCHARS=${WORDCHARS//[\/]} # remove path separators

# autoload -U zmv
# zmv '* *' '$f:gs/ /_' # replace spaces with underscores in filenames

ZSH_AUTOSUGGEST_MANUAL_REBIND=1 # disable automatic widget re-binding on precmd
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

zmodload -F zsh/terminfo +p:terminfo

eval "$(zoxide init zsh --cmd cd)"

source ~/.config/zsh/prompt.zsh # <-- cmdline prompt here
source ~/.config/zsh/completion.zsh

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]"  history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

export TERM="rxvt-256color"

export FZF_DEFAULT_OPTS="
--color fg:#D8DEE9,bg:#2E3440,hl:#A3BE8C,fg+:#D8DEE9,bg+:#434C5E,hl+:#A3BE8C
--color pointer:#BF616A,info:#4C566A,spinner:#4C566A,header:#4C566A,prompt:#81A1C1,marker:#EBCB8B
--bind 'alt-j:preview-down,alt-k:preview-up,ctrl-f:preview-page-down,ctrl-b:preview-page-up'
"
export FZF_DEFAULT_COMMAND="fd -tf -tl -H --exclude .git node_modules"

export PATH="/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$HOME/builds/bin:$HOME/.cargo/bin"

export CC="cc"
export CXX="c++"
export EDITOR="nvim"
export CARGO_TARGET_DIR="$HOME/.cargo/builds"

export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
MOZ_ENABLE_WAYLAND=1

alias ls="eza -lhoF --no-permissions --git --no-user"
alias cat="bat --theme Nord"
# alias glow="glow --config ~/.config/glow/glow.yml"
# alias fb="buku -p -f5 | column -ts $'\t' | fzf -m | cut -d ' ' -f1 | buku -o"
# alias fa="fd .  -t x -t l $(echo $PATH | sed 's_:_\ _g') | grep -o '[^/]*$' | fzf --preview='man {}'"
