setopt HIST_IGNORE_ALL_DUPS # ignore all duplicate history entries
setopt CORRECT # spelling correction prompt
bindkey -v # vi editor default keymap

SPROMPT='zsh: correct %F{red}%R%f to %F{green}%r%f [nyae]? '

WORDCHARS=${WORDCHARS//[\/]} # remove path separators

# autoload -U zmv
# zmv '* *' '$f:gs/ /_' # replace spaces with underscores in filenames

ZSH_AUTOSUGGEST_MANUAL_REBIND=1 # disable automatic widget re-binding on precmd
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)

zmodload -F zsh/terminfo +p:terminfo

eval "$(zoxide init zsh --cmd cd)"

# -- sourcing external files
# TODO: add vi-mode prompt (<)
source ~/.config/zsh/prompt.zsh # <-- cmdline prompt here
source ~/.config/zsh/completion.zsh

source "$HOME/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
source "$HOME/.config/zsh/zsh-history-substring-search/zsh-history-substring-search.zsh"
source "$HOME/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh"

bindkey "$terminfo[kcuu1]" history-substring-search-up
bindkey "$terminfo[kcud1]"  history-substring-search-down
bindkey -M vicmd 'k' history-substring-search-up
bindkey -M vicmd 'j' history-substring-search-down

export FZF_DEFAULT_OPTS="
--color fg:7,hl:2,fg+:7,bg+:0,hl+:2
--color pointer:4,info:7,spinner:0,header:4,prompt:4,marker:3
--bind 'alt-j:preview-down,alt-k:preview-up,ctrl-j:preview-page-down,ctrl-k:preview-page-up'
"
export FZF_DEFAULT_COMMAND="rg --files --hidden --follow --glob '!.git'"

export PATH="/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:$HOME/builds/bin:$HOME/.cargo/bin:$JAVA_HOME/bin:$HOME/.local/bin:$HOME/go/bin"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
export PYTHONPATH="$PYTHONPATH:$HOME/Documents/neko_python/venv/lib/python3.12/site-packages"

export CC="cc"
export CXX="c++"
export EDITOR="nvim"
export CARGO_TARGET_DIR="$HOME/.cargo/builds"

export DEBUGINFOD_URLS="https://debuginfod.archlinux.org"
MOZ_ENABLE_WAYLAND=1

alias ls="eza -lhoF --no-permissions --git --no-user"
alias cat="bat --style grid,numbers,changes --theme base16"
alias ffzf="exec ~/.config/zsh/explorer.sh"

alias dnf_pkg_size_ls="dnf repoquery -C --installed --qf '%{size} %{name}' | sort -n | numfmt --to=iec --format='%.2f'"
alias dnf_userpkg_size_ls="dnf repoquery -C --userinstalled --qf '%{size} %{name}' | sort -n | numfmt --to=iec --format='%.2f'"
# alias fb="buku -p -f5 | column -ts $'\t' | fzf -m | cut -d ' ' -f1 | buku -o"
# alias fa="fd .  -t x -t l $(echo $PATH | sed 's_:_\ _g') | grep -o '[^/]*$' | fzf --preview='man {}'"
